name: Build TopChina Proxies

on:
  workflow_dispatch:
  schedule:
    - cron: "*/45 * * * *"  # 每45分钟左右（在每小时的0分与45分运行）

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests

      - name: Generate proxies.yaml and sync README.md
        run: python scripts/build_proxies.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add proxies.yaml README.md
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "chore: update proxies.yaml and sync README.md"
            git push
          fi
